import type { NextPage } from 'next';
import Head from 'next/head';
import RandomFox from '@/components/RandomFox';
import { MouseEventHandler, useState } from 'react';

const random = (): number => Math.floor(Math.random() * 123) + 1;
const generateID =  (): string => Math.random().toString(36).substring(2,9)

type ImageItem = { id:string, image:string }

const Home: NextPage = (): JSX.Element => {
  const [images, setImages] = useState<ImageItem[]>([])

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) : void => {
    const image = `https://randomfox.ca/images/${random()}.jpg`;
    const newImageItem: ImageItem = {
      id: generateID(),
      image
    }
    setImages([...images, newImageItem]);
  };
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <button onClick={addNewFox}>add new fox</button>
        {images.map(({image, id}) => (
          <div className="p-4" key={id}>
            <RandomFox image={image} />
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
