import type { NextPage } from 'next';
import Head from 'next/head';
import RandomFox from '@/components/RandomFox';

const random = (): number => Math.floor(Math.random() * 123) + 1;

const Home: NextPage = (): JSX.Element => {
  const image = `https://randomfox.ca/images/${random()}.jpg`;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <RandomFox image={image}/>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
